"""
External API clients for cloud-based generation services.

Image Generation APIs:
- DALL-E 3 (OpenAI): https://platform.openai.com/docs/guides/images
- Gemini (Google): https://ai.google.dev/gemini-api/docs/image-generation

3D Generation APIs:
- Tripo3D: https://platform.tripo3d.ai/docs/generation
"""
import base64
import io
import logging
import tempfile
import time
from typing import Optional, Tuple

import requests
from PIL import Image

from .config import settings

logger = logging.getLogger(__name__)


# =============================================================================
# Image Generation APIs
# =============================================================================

class DalleAPIClient:
    """
    Client for OpenAI DALL-E API (image generation)

    API Reference: https://platform.openai.com/docs/guides/images

    Models:
    - dall-e-3: 1024x1024, 1792x1024, 1024x1792
    - dall-e-2: 256x256, 512x512, 1024x1024

    Parameters:
    - quality: "standard" or "hd"
    - style: "vivid" or "natural"
    """

    BASE_URL = "https://api.openai.com/v1"

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

    def generate_image(
        self,
        prompt: str,
        size: str = "1024x1024",
        quality: str = "standard",
        style: str = "vivid"
    ) -> Image.Image:
        """
        Generate image from text prompt using DALL-E 3.

        Args:
            prompt: Text prompt
            size: "1024x1024", "1792x1024", "1024x1792"
            quality: "standard" or "hd"
            style: "vivid" or "natural"

        Returns:
            PIL Image
        """
        logger.info(f"[DALL-E 3] Generating image: {prompt[:50]}...")

        response = requests.post(
            f"{self.BASE_URL}/images/generations",
            headers=self.headers,
            json={
                "model": "dall-e-3",
                "prompt": prompt,
                "n": 1,
                "size": size,
                "quality": quality,
                "style": style,
                "response_format": "b64_json"
            }
        )
        response.raise_for_status()

        data = response.json()["data"][0]
        image_data = data["b64_json"]
        revised_prompt = data.get("revised_prompt", prompt)

        image = Image.open(io.BytesIO(base64.b64decode(image_data)))
        logger.info(f"[DALL-E 3] Generated! Revised: {revised_prompt[:50]}...")

        return image


class GeminiAPIClient:
    """
    Client for Google Gemini API (image generation)

    API Reference: https://ai.google.dev/gemini-api/docs/image-generation

    Models:
    - gemini-2.0-flash-exp (image generation)

    Parameters:
    - responseModalities: ["TEXT", "IMAGE"]
    """

    BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_image(
        self,
        prompt: str,
        aspect_ratio: str = "1:1"
    ) -> Image.Image:
        """
        Generate image from text prompt using Gemini.

        Args:
            prompt: Text prompt
            aspect_ratio: "1:1", "16:9", "4:3", "3:4", "9:16"

        Returns:
            PIL Image
        """
        logger.info(f"[Gemini] Generating image: {prompt[:50]}...")

        url = f"{self.BASE_URL}/models/gemini-2.0-flash-exp:generateContent"
        headers = {
            "Content-Type": "application/json",
            "x-goog-api-key": self.api_key
        }

        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }],
            "generationConfig": {
                "responseModalities": ["TEXT", "IMAGE"]
            }
        }

        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()

        result = response.json()
        candidates = result.get("candidates", [])

        if not candidates:
            raise Exception("No image generated by Gemini")

        # Find image in response parts
        parts = candidates[0].get("content", {}).get("parts", [])
        for part in parts:
            if "inlineData" in part:
                image_data = part["inlineData"]["data"]
                image = Image.open(io.BytesIO(base64.b64decode(image_data)))
                logger.info("[Gemini] Image generated!")
                return image

        raise Exception("No image found in Gemini response")


# =============================================================================
# 3D Generation APIs
# =============================================================================

class TripoAPIClient:
    """
    Client for Tripo3D API (image to 3D)

    API Reference: https://platform.tripo3d.ai/docs/generation
    Python SDK: https://github.com/VAST-AI-Research/tripo-python-sdk

    Parameters:
    - model_version: "v2.0-20240919"
    - face_limit: Max polygon count
    - texture_alignment: "original_image" or "geometry"
    """

    BASE_URL = "https://api.tripo3d.ai/v2/openapi"

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.headers = {
            "Authorization": f"Bearer {api_key}",
        }

    def _upload_image(self, image: Image.Image) -> str:
        """Upload image and return file token."""
        buf = io.BytesIO()
        image.save(buf, format="PNG")
        buf.seek(0)

        files = {"file": ("image.png", buf, "image/png")}
        response = requests.post(
            f"{self.BASE_URL}/upload",
            headers=self.headers,
            files=files
        )
        response.raise_for_status()
        return response.json()["data"]["image_token"]

    def image_to_3d(
        self,
        image: Image.Image,
        face_limit: int = 100000,
        texture_alignment: str = "original_image"
    ) -> Tuple[str, str]:
        """
        Generate 3D model from image.

        Args:
            image: PIL Image (RGBA recommended)
            face_limit: Max polygon count
            texture_alignment: "original_image" or "geometry"

        Returns:
            Tuple of (obj_path, glb_path)
        """
        logger.info("[Tripo API] Uploading image...")

        file_token = self._upload_image(image)
        logger.info(f"[Tripo API] Uploaded, token: {file_token[:20]}...")

        # Create task
        task_payload = {
            "type": "image_to_model",
            "file": {"type": "image", "file_token": file_token},
            "model_version": "v2.0-20240919",
            "face_limit": face_limit,
            "texture_alignment": texture_alignment,
        }

        logger.info("[Tripo API] Creating task...")
        task_response = requests.post(
            f"{self.BASE_URL}/task",
            headers={**self.headers, "Content-Type": "application/json"},
            json=task_payload
        )
        task_response.raise_for_status()
        task_id = task_response.json()["data"]["task_id"]
        logger.info(f"[Tripo API] Task: {task_id}")

        # Poll for completion
        start_time = time.time()
        while time.time() - start_time < 600:
            status_response = requests.get(
                f"{self.BASE_URL}/task/{task_id}",
                headers=self.headers
            )
            status_response.raise_for_status()
            status_data = status_response.json()["data"]

            status = status_data.get("status", "unknown")
            progress = status_data.get("progress", 0)

            if status == "success":
                logger.info("[Tripo API] Complete!")
                break
            elif status == "failed":
                raise Exception(f"Tripo failed: {status_data.get('message')}")

            logger.info(f"[Tripo API] {status} ({progress}%)")
            time.sleep(5)
        else:
            raise Exception("Tripo API timeout")

        # Download
        model_data = status_data.get("output", {}).get("model", {})
        glb_url = model_data.get("url")
        if not glb_url:
            raise Exception("No model URL")

        glb_file = tempfile.NamedTemporaryFile(suffix=".glb", delete=False)
        glb_response = requests.get(glb_url)
        glb_response.raise_for_status()
        glb_file.write(glb_response.content)
        glb_file.close()

        obj_file = tempfile.NamedTemporaryFile(suffix=".obj", delete=False)
        obj_file.write(glb_response.content)
        obj_file.close()

        logger.info(f"[Tripo API] Downloaded: {len(glb_response.content)} bytes")
        return obj_file.name, glb_file.name


# =============================================================================
# Factory Functions
# =============================================================================

def get_dalle_client() -> Optional[DalleAPIClient]:
    """Get DALL-E client if configured."""
    if settings.openai_api_key:
        return DalleAPIClient(settings.openai_api_key)
    return None


def get_gemini_client() -> Optional[GeminiAPIClient]:
    """Get Gemini client if configured."""
    if settings.gemini_api_key:
        return GeminiAPIClient(settings.gemini_api_key)
    return None


def get_tripo_client() -> Optional[TripoAPIClient]:
    """Get Tripo client if configured."""
    if settings.tripo_api_key:
        return TripoAPIClient(settings.tripo_api_key)
    return None
